#!/bin/bash

host=127.0.0.1
firstport=10
lastport=500
ip=$(hostname -I | cut -c1-10)

function portscan {
for ((counter=$firstport; counter<=$lastport; counter++))
	do
		(echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 && echo "$counter open"
	done 
}

if type -t wevtutil &> /dev/null
then
	OS=MSWin
elif type -t scutil &> /dev/null
then
	OS=macOS
else
	OS=Linux
fi

function netsca() {
	  ping -c 1 $1 > /dev/null 2>&1
	  [ $? -eq 0 ] && echo "This IP: $i is up."
}

function general() {
echo "El sistema operativo es: "$OS
echo "Los puertos abiertos en Local host son: "
portscan 127.0.0.1 $firstport $lastport
echo "La IP es:" $(hostname -I | cut -c1-13)
echo "Buscando..."
for i in "$ip"{1..255}
do
if (netsca $i & disown)
	then
		for ((counter=$firstport; counter<=$lastport; counter++))
	        do
	                (echo >/dev/tcp/$i/$counter) > /dev/null 2>&1 && echo "$counter open"
		done
		break
	fi
done
}

general > info.txt


